### ISSUE TITLE
Lessmsi Explore Failure

### ISSUE THREAD

**Issue by computer-dave** [activescott/lessmsi#100]
Hello, just installed lessmsi v1.6.1 using choco and ran into a bug. I ran lessmsi-gui, then went to Edit | Preferences and added the Shortcut Item(s) to Explorer. I then used Windows Explorer to navigate to the folder that was created when I unzipped a recent download, right-clicked on the msi file and selected Lessmsi Explore. What looked like a DOS window flashed on the screen briefly, then the gui was displayed, but it did not open the msi file. At the bottom of the window there was an error message indicating that the download folder did not exist (even though alt-tab switches right to it in an open Explorer window)...

The actual error message text displayed was 

"_ERROR:File "C:\Users\Username\Downloads\!" does not exist._" 

It appears that LessMSI does not properly support long file names (i.e. embedded spaces), as the name of the folder containing the MSI I was trying to open is 

"_C:\Users\dllevine\Downloads\! NEW (Unsorted)_" 

It's definitely the embedded space that's the issue - I moved the MSI file to a nice, sensibly-named folder, "_c:\temp_" and repeated the above steps and LessMSI was able to open the file without any issues. 

I use various punctuation marks at the beginning of many of my folder names to ensure that they sort the way I want them to, (i.e. "!" sorts at the top of the list before "A"), and I also rename everything that I download with the actual application name and version (trying to decrypt 8.3 is so pre-Y2K... lol), so the name of pretty much any file that I might be inclined to browse with lessmsi is going to have at least one (though typically more) embedded space. When I go to extract any of the zip files I've downloaded, the folders that get created are names after the zip file, thus the spaces are in the folder names as well. 

To use lessmsi as an example, before I installed it using choco, I downloaded the lessmsi zip file. When the download prompt asked me for a filename, it went something like this - 
lessmsi was renamed from "_lessmsi-v1.6.1.zip_" to "_LessMSI v1.6.1 (lessmsi-v1.6.1).zip_"
this, in turn, created a folder named "_LessMSI v1.6.1 (lessmsi-v1.6.1)_" when it was extracted. 

If there was an msi file in there that I wanted to look at, I'd hit an error there too. :(

Hopefully it won't be too difficult to fix this issue - I suspect that I can't be the only person who's encountered it.

Regards,
- Dave

**Comment by activescott** [comment]
Thanks for the detailed notes Dave. I'll take a look as soon as I have a chance to spend some time on this project.

**Comment by DarrenWhite99** [comment]
I just had this same issue, but the space was in the filename. It reported that the file could not be found and displayed the name up to the space. The filename was like: "C:\users\me\downloads\agentinstall (1).msi" and it said that it could not open "C:\users\me\downloads\agentinstall".

**Comment by bhattumang7** [comment]
@activescott I have got a fix for this. Can you please make changes to allow me to push?

**Comment by activescott** [comment]
@DarrenWhite99 @bhattumang7 First, I believe this may have been addressed in released v1.6.2 released yesterday at https://github.com/activescott/lessmsi/releases/tag/v1.6.2 which included PR #86 from another contributor. Can you please confirm one way or the other?

@bhattumang7 I accept pull requests. To get your changes in, please submit a pull request (PR) and I'll be more than happy to review and accept it! More information about how to create a pull request is at https://help.github.com/articles/creating-a-pull-request/

**Comment by bhattumang7** [comment]
I agree. This bug is fixed in new release. We can close this.
