### ISSUE TITLE
Random crashing

### ISSUE THREAD

**Issue by kevlarballoons** [activescott/lessmsi#102]
If you try to extract most of the files in an MSI, it'll crash
![capture](https://user-images.githubusercontent.com/20979571/34565674-be781b7c-f129-11e7-8081-5cf547ac1c48.PNG)

**Comment by activescott** [comment]
@kevlarballoons  This appears to be specific to your MSI. Can you please reply with a link to the exact MSI you're having trouble with?

**Comment by activescott** [comment]
need more info to repro
