### ISSUE TITLE
Extracting 32bit and 64bit directory

### ISSUE THREAD

**Issue by UNiXMIT** [activescott/lessmsi#107]
The MSI I am trying to extract installs a bin directory in C:\Program Files (x86) and a bin directory in C:\Program Files. So when I extract this MSI I get one bin directory with double the amount of files and half of them have the extension .duplicate1. Is there something I can do to stop this or does the issue lie with the MSI?
Thanks

**Comment by activescott** [comment]
Not sure - it depends on how the MSI package author did things. Please attach or link to the msi and maybe someone can take a look. Feel free to re-open the issue with more info.
