### ISSUE TITLE
"The operation completed successfully" error

### ISSUE THREAD

**Issue by voltagex** [activescott/lessmsi#123]
**Describe the bug**

**To Reproduce**
1. Download https://download.microsoft.com/download/4/2/2/42245968-6A79-4DA7-A5FB-08C0AD0AE661/windowssdk/Installers/Windows%20SDK%20Desktop%20Headers%20x64-x86_en-us.msi

2. Attempt to extract ksamd64.inc

**Expected behavior**
File is extracted

**Screenshots**

![image](https://user-images.githubusercontent.com/159567/59042240-6ec34c00-88bd-11e9-82e8-0226fc95394a.png)

```
---------------------------
MSI Error!
---------------------------
Please report this error at https://github.com/activescott/lessmsi/issues . Include the exact error message and how to get a copy of the msi you're working with.

The following error occured extracting the MSI: System.Exception: Error copying file 'C:\Users\Adam\Downloads\Windows Kits\10\WindowsSDK\Installers\e5950ce9ba509b3370ebf328742a5f45.cab' to 'C:\Users\Adam\Downloads\Windows Kits\10\WindowsSDK\Installers\e5950ce9ba509b3370ebf328742a5f45.cab'. System error information:'The operation completed successfully.

'

   at LessIO.Strategies.Win32.Win32FileSystemStrategy.Copy(Path source, Path dest)

   at LessMsi.Msi.Wixtracts.CabsFromMsiToDisk(Path msi, Database msidb, String outputDir)

   at LessMsi.Msi.Wixtracts.ExtractFiles(Path msi, String outputDir, MsiFile[] filesToExtract, AsyncCallback progressCallback)

   at LessMsi.Gui.MainForm.btnExtract_Click(Object sender, EventArgs e)
---------------------------
OK   
---------------------------

```
**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 
lessmsi 1.6.3

**Comment by voltagex** [comment]
Ran into another example of this:
https://download.microsoft.com/download/a/a/c/aac39226-8825-44ce-90e3-bf8203e74006/dotnetfx.exe

Extract the MSI out of dotnetfx.exe using 7-zip, then try to extract msvcr71.dll out of the MSI using lessmsi.

**Comment by jjurkus** [comment]
The Windows SDK Desktop Headers x64-x86_en-us.msi file is looking for an external .cab file where this file is located. If you open the msi file in 7-zip you can see there is no file of roughly that size.
But I have seen this problem before, also with a windows 10 thing, the ADK (something something deployment kit). If you download the entire suite, then it will probably also include the needed .cab files. Why microsoft puts this msi file on their download site... just another one of their infinite wisdoms, I suppose.

With the dotnetfx.exe it's almost the same story. The file isn't there. Not in the cab file, and not in the msi file. If you open the msi file with orca or insted and look at various tables, you can see this msi is a piece of crap. The InstallExecuteSequence is a goldmine of simplicity. There are a lot of conditions like this:
```
($ASPNET_REGIIS_EXE_____X86.3643236F_FC70_11D3_A536_0090278A1BB8 > 2) AND ( NOT NOASPUPGRADE )
($ASPNET_MOF________.3643236F_FC70_11D3_A536_0090278A1BB8 = 2) AND ( MOFCOMP_EXE.3643236F_FC70_11D3_A536_0090278A1BB8 )
```
The customaction table is also filled with a metric shitton of hideousness. I think the msvcr71.dll was once part of the msi file, but there are probably some conditions that will make it to never to be installed, and eventually they didn't include the file, and no problem was ever reported.
Stuff like this happens a lot. Imagine a cad program that hasn't supported XP for years, that still includes all the dependencies. adobe photoshop sometimes outputs debug messages, the released build was never compiled without the debug flag. And I recently packed some software from 2018 that still included dependencies for windows 95.

**Comment by activescott** [comment]
I checked both the netfx.exe and Windows%20SDK%20Desktop%20Headers%20x64-x86_en-us.msi files and as @jjurkus explained they are definitely referencing cab files that do not exist in the MSI. I'm guessing that when you execute those .msi files (or the dotnetfx.exe file) it actually downloads the cab from the internet and _then_ the msi extraction logic could proceed normally. However, in this case those files you're after are not actually inside the MSI so nothing lessmsi can do here.
