### ISSUE TITLE
Gotta say it: Brilliant project name!

### ISSUE THREAD

**Issue by Ander3232** [activescott/lessmsi#128]
Hey guys,

This isn't a bug, but the site (lessmsi.activescott.com) said I could post "suggestions, problems, comments" here, so I hope it's okay.

As a writer/editor, I had to rave about your brilliant project name. "Less MSIerables" (short version: LessMSI). Man! When I saw that, it stopped me in my tracks. I don't know about you, but it's the first software name _I've_ ever seen that achieved a pun on a computing acronym by means of a Broadway show title—and as if that weren't enough, it even makes a pun on the show title itself ("Les" -> "Less")! If you're as good at writing code as you are at thinking of immensely clever product names, you have nothing to worry about.

With sincere admiration, following initial astonishment that coders could be that funny, A.

**Comment by activescott** [comment]
😆 👍
