### ISSUE TITLE
Failed to extract files from msi in vcredist2005/2008/2010

### ISSUE THREAD

**Issue by linsui** [activescott/lessmsi#129]
**Describe the bug**
Failed to extract files from msi in vcredist2005/2008/2010

**To Reproduce**
1. Download https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x64.exe for example.
2. Extract vc_red.msi and vc_red.cab from vcredist_x64.exe\\.\\.\\.\\.\\ with 7zip
3. Extract files from vc_red.msi

**Screenshots**

![2019-10-26 12_36_39-New Issue · activescott_lessmsi](https://user-images.githubusercontent.com/36977733/67614369-6eafe400-f7ab-11e9-9df5-c40861fc6e2a.png)

**Comment by jjurkus** [comment]
No issues with 1.6.91 on an english windows 7 x64. Have you used the most recent version?

**Comment by linsui** [comment]
Thanks! It works. I don't know why...
