### ISSUE TITLE
Cab file does not exist

### ISSUE THREAD

**Issue by cup** [activescott/lessmsi#131]
If I try to extract a certain file:

~~~
lessmsi x windows%20sdk%20desktop%20libs%20x64-x86_en-us.msi
~~~

I get this message:
   
~~~
Error: System.Exception: The file "C:\sdk\58314d0646d7e1a25e97c902166c3155.cab"
does not exist.
~~~

Fair enough, but does LessMsi have a way to list all the files that are
required?

**Comment by cup** [comment]
This seems to do it:

~~~sh
lessmsi l -t Component sunday.msi | sed '
/dirCatalogRepositoryDirectory/!d
s/sca//
s/,.*//
'
~~~

**Comment by activescott** [comment]
Hey there @cup ! Yep, you can list the files on the command line ([docs](https://github.com/activescott/lessmsi/wiki/Command-Line)) or in the GUI there is a "Extract Files" tab that should show them to you.

If you think there is a bug/error in the program related to that msi, please feel free to re-open this issue and attach that msi and I'll look into it.

Thanks for leaving a comment!

**Comment by cup** [comment]
@activescott this isnt about extracting files, it about dealing with MSI that require external CAB files

**Comment by 89z** [comment]
Here is another way to do this, using Python:

~~~py
import msilib
path = 'Windows SDK for Windows Store Apps Headers-x86_en-us.msi'
db = msilib.OpenDatabase(path, msilib.MSIDBOPEN_DIRECT)
view = db.OpenView('SELECT * FROM Media')
view.Execute(None)

while True:
   rec = view.Fetch()
   if rec is None:
      break
   print(rec.GetString(4))
~~~
