### ISSUE TITLE
Failed to extract files from PBIDesktop_x64.msi

### ISSUE THREAD

**Issue by StrollStars** [activescott/lessmsi#133]
**Describe the bug**
Failed to extract files from PBIDesktop_x64.msi

**To Reproduce**
1. Download the [PBIDesktop_x64.part1.rar](https://app.box.com/s/lyiifz02lzfgvnyarw8g9yxs4dfnt1k3) and [PBIDesktop_x64.part2.rar](https://app.box.com/s/n54fzd5nfun21yxl8whqqgeg3x9uuyy4)
2. Unzip the two rar files
3. Extract files from PBIDesktop_x64.msi

**Screenshots**
![1](https://user-images.githubusercontent.com/10942225/73121631-0ee9f480-3fb7-11ea-8d85-eb36d42cb882.jpg)

**Desktop (please complete the following information):**
 - OS: Win7 x64

**Comment by activescott** [comment]
Thank you for the report. I'll download those files and check this out as soon as I have a moment.

**Comment by jjurkus** [comment]
I downloaded those files, no issues here with 1.6.91 and an english windows 7 x64.

**Comment by StrollStars** [comment]
@jjurkus Thank you for your help, today I tried again, found no problem, it is very strange.

**Comment by StrollStars** [comment]
@jjurkus I'm having this problem again, and after using the search function, an error occurred while exporting.

**Comment by StrollStars** [comment]
I reproduced the error. This error occurs if I extract the msi file to the root directory of disk partition(there is enough space).

**Comment by StrollStars** [comment]
@jjurkus I reproduced the error. This error occurs if I extract the msi file to the root directory of disk partition(there is enough space).

**Comment by activescott** [comment]
Thanks for reporting it and noting that it is due to the drive root being the extraction directory.

This appears to be rooted in activescott/lessio#10 . I have a fix that I'm working on over there in activescott/lessio#11 . Once I confirm that is all passing and the package is published for lessio I'll rebuild and republish this fix with lessmsi. Should be tomorrow or over the weekend 🤞

**Comment by StrollStars** [comment]
@activescott Thank you very much.
