### ISSUE TITLE
Nothing in the Thunderbird Setup 68.7.0

### ISSUE THREAD

**Issue by StrollStars** [activescott/lessmsi#136]
There's nothing in the [Thunderbird Setup 68.7.0](https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/68.7.0/win64/zh-CN/Thunderbird%20Setup%2068.7.0.msi).

Desktop (please complete the following information):
OS: Win7 x64

**Comment by jjurkus** [comment]
This is because the firefox and thunderbird msi files are just a wrapper around the .exe file.
If you want any files from thunderbird, just download the exe file and extract with 7zip.

**Comment by StrollStars** [comment]
@jjurkus Thanks, I got it.
