### ISSUE TITLE
Extract Error

### ISSUE THREAD

**Issue by DesiredCall** [activescott/lessmsi#141]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version v1.6.3

What happened was is that I wanted to do a TitleUpdate.MSI To downgrade my GTAIV What happened is that it could not and it came up with a error and it directed me to this website.

Screenshot: 
![error](https://user-images.githubusercontent.com/67890385/86578739-a3716d80-bfbf-11ea-96ba-191cf8ea153e.PNG)

If anybody has any idea or clue what to do please help me.

**Comment by activescott** [comment]
Not sure. Could you possibly post a link to the msi you're having a problem with or attach it so that we can reproduce?

**Comment by DesiredCall** [comment]
https://github.com/activescott/lessmsi/releases/tag/v1.6.91
@activescott Sorry for late response

**Comment by DesiredCall** [comment]
https://www.youtube.com/watch?v=dsE-5Wz6wRc&t=84s

**Comment by jjurkus** [comment]
If you first extract all files from the archive, lessmsi will extract it fine without errors.

**Comment by DesiredCall** [comment]
Thank you so much.

**Comment by activescott** [comment]
Thanks @jjurkus for a solution! and @DesiredCall for reporting. So was there something that we should improve/fix in lessmsi to make this better?

**Comment by jjurkus** [comment]
@activescott
Not much. Maybe change/create a specific error message if a particular .cab file can't be found.
I got it from here: https://www.download3k.com/Install-Grand-Theft-Auto-4-Patch.html
I don't know if this is an official patch, but that youtube video shows a modification being done to this patch, perhaps to turn off auto-updating. Something like that.

If a cab file is referenced in the msi file and the file is there the extraction normally works.

**Comment by activescott** [comment]
Closing this one and using #148 to track the improvement to add specific error message if a particular external .cab file can't be found.
