### ISSUE TITLE
Cannot open 'MicrosoftEdgeEnterpriseX64.msi' (v97.0.1072.55)

### ISSUE THREAD

**Issue by niheaven** [activescott/lessmsi#173]
**Describe the bug**

lessmsi cannot open recent `MicrosoftEdgeEnterpriseX64.msi`

**To Reproduce**
1. Go to 'https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/4726286f-d08f-4d1c-9d86-8cc88d8ca208/MicrosoftEdgeEnterpriseX64.msi'
2. Drag 'n drop this file into Lessmsi, nothing happened
3. `lessmsi MicrosoftEdgeEnterpriseX64.msi` output null

**Screenshots**

![image](https://user-images.githubusercontent.com/5832170/149341441-a2af5df5-4a3e-4924-b61a-2c8c48937d78.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro Insider PreviewBuild 22526

**Comment by jjurkus** [comment]
This is because the msi has no files in it, it is just a wrapper for an installer in a customaction table. The installer contains all the files. So you could just as well take the .exe version and see if you can extract that.

**Comment by activescott** [comment]
Thanks @jjurkus !! 🙌  

@niheaven If you think we're missing something here, feel free to leave a comment and reopen the issue. Thanks for submitting though.
