### ISSUE TITLE
Not working any more for all .msi packages

### ISSUE THREAD

**Issue by pstein** [activescott/lessmsi#176]
Have a look at this free software:

https://github.com/emoacht/Wifinian/releases

After extracting the *.zip files I got an *.msi file.

This file cannot be extracted DIRECTLY with LessMSI Extract.
I have to first show the content, mark the files and then extract the content.

Could you make it directly extractable?

**Comment by activescott** [comment]
Hi @pstein 👋 Can you please clarify what you mean by "directly extractable"? Do you want to not have to show the content and mark the files?

**Comment by pstein** [comment]
Directly extractable means: be able to right click on a .msi file and select "Lessmsi extract files" Windows Explorer context menu and let it extract. When I select it currently a milliseconds flash appears but no extract happens.

I have to select "Lessmsi Explore" context menu, then click on "Select All" button and then "Extract" Button to really extract all files.

**Comment by activescott** [comment]
I couldn't reproduce this today using the latest lessmsi.
[Uploading worksonmymachine.webm…]()
