### ISSUE TITLE
How to deploy leemsi on linux?

### ISSUE THREAD

**Issue by def-fun** [activescott/lessmsi#178]
Hi, my ubuntu nas stored lots of msi installer. Now I have to verify their integrity (not damaged) before backup. I have no md5sum/sha1sum of them. So I think lessmsi might be a good choice.

Can you provide some suggestion?

**Comment by gxgl** [comment]
Hello,

if your nas runs ubuntu then maybe you can try installing msitools package directly provided by the os.

Try:
`sudo apt-get install msitools`
or
`sudo apt install msitools`

Hope this helps.

All the best,
George

**Comment by activescott** [comment]
msitools might be better. I'm not sure though. lessmsi does not provide this capability.

**Comment by gxgl** [comment]
Hi Scott,

lessmsi also works, but there is need to install mono and build tools first, then clone lessmsi, compile and run 👍

msitools will be straight forward for users don't know how to do the steps above.

In my case, I don't know how to help creating a package (deb, rpm, etc) with respective dependencies to provide it, but it will be great if someone else could do it.

Anyway, lessmsi is a great code! 👍

All the best,
George

**Comment by timur-g** [comment]
> lessmsi also works, but there is need to install mono and build tools first, then clone lessmsi, compile and run 👍
Can you please explain how to comple lessmsi?
