### ISSUE TITLE
Error closing lessmsi-gui - permission issue

### ISSUE THREAD

**Issue by Nurple** [activescott/lessmsi#190]
**Describe the bug:**
Heya, since updating to v1.11.0, closing lessmsi is causing an error as it tries to write to lessmsi-gui.exe.config in the "install" directory, which fails as it's write protected. 

**To Reproduce:**
1. Open lessmsi-gui
2. Move / Resize window
3. Close lessmsi-gui

**Expected behavior:**
Save the window size / position settings under C:\Users\\~\AppData\Local\LessMsi like other settings.

**Screenshot:**

![Error](https://github.com/activescott/lessmsi/assets/1991704/de72f7d0-3de2-4fa5-8812-81182f2c248f)

**Desktop:**
 - OS: Windows 10 - 22H2

**Comment by activescott** [comment]
@Nurple Thank you for reporting and sorry about the trouble. We'll get it fixed up! 

@mega5800 Can you please investigate. I should have thought more about the location of saving. You can see how other settings are saved in the `LoadPreferences` and `SavePreferences` method at https://github.com/activescott/lessmsi/blob/83e57cf400bc2b6fe2727907304e3641e01293a4/src/LessMsi.Gui/MruMenuStripManager.cs#L67 Can you please change to using that general technique for persisting settings?

**Comment by mega5800** [comment]
@activescott @Nurple 
Thank you for bringing this matter to my attention, and sorry for any inconvenience caused.
I will investigate this issue during the weekend, and hopefully will have a fix by Monday.

**Comment by activescott** [comment]
Thanks @mega5800 - Not super urgent from my side. If you feel like it's taking you too long or you want a hand let me know! Thanks again!!

**Comment by Nurple** [comment]
Thanks for the fix.
