### ISSUE TITLE
update command-line help wiki with flat extraction help

### ISSUE THREAD

**Issue by activescott** [activescott/lessmsi#199]
@mega5800 Can you please update https://github.com/activescott/lessmsi/wiki/Command-Line with the appropriate documentation for the flat extraction feature from #197

**Comment by mega5800** [comment]
Hello @activescott.

You can assign this ticket to me if you'd like.
I can take care of this matter during this weekend.

Thank you.

**Comment by activescott** [comment]
Thanks!

**Comment by mega5800** [comment]
@activescott
Just added two new sections for the xfo & xfr commands in the command line wiki.
Please review it and let me know if you want something else added there.

Thanks.

**Comment by activescott** [comment]
Awesome! Thank you!!
