### ISSUE TITLE
make GUI multilanguage

### ISSUE THREAD

**Issue by bovirus** [activescott/lessmsi#203]
@mega5800 

**Describe the bug**
Bug is "GUI only English".

**To Reproduce**

**Expected behavior**
Modify the source to make GUI multilanguage.
I can help to translate it into Italian.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 64bit italian
 - Browser: Gooigle Chrome
 - Version 126.0.6478.183

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mega5800** [comment]
Thank you for your suggestion.
I believe it could be beneficial not only for Italian users but also for users from other countries, as this work will pave the way for other GUI languages.

The first step would be to map all the different English texts in the GUI app.

Main Form:
![image](https://github.com/user-attachments/assets/8d72f173-2638-43d3-9bb0-c211264b84ad)

File Sub Menu:
![image](https://github.com/user-attachments/assets/3aac3c11-8a38-4aaa-99c4-284a7463245f)

Edit Sub Menu:
![image](https://github.com/user-attachments/assets/7d0d83c2-089a-43a8-be49-0d8419aa3ebd)

About Sub Menu:
![image](https://github.com/user-attachments/assets/a39116bb-ed99-4a07-aa82-09be55304b24)

Table View Tab:
![image](https://github.com/user-attachments/assets/faf31b81-be69-4f99-bb9e-dc7c4d506404)

Summary Tab:
![image](https://github.com/user-attachments/assets/19b56cb6-1490-45af-a158-a98fc1be9c0e)

Streams Tab:
![image](https://github.com/user-attachments/assets/6210fda9-05da-4432-9c76-33772edf30ba)

@bovirus and @activescott, please let me know if I missed any other English text.
bovirus, please let me know if you can translate the marked texts to Italian and send them as a comment for this initial stage.

**Comment by bovirus** [comment]
@mega5800

Thanks for the opportunity.

File=File
Edit=Modifica
About=Info programma
Extract Files=Estrai file
Table View=Vista tabella
Streams=Flussi
Name=Nome
Directory=Cartella
Component=Componente
Size=Dimensione
Version=Versione
Seelct All=Selziona tutto
Deselct all=Deseleziona tutto
Open=Apri
<Recent Files>=<File recenti>
Exit=Esci
Copy=Copia
Preferennces=Preferenze
Search file=Cerca file
About Less MSieérables [lessmsi] GUI Interface=Info interfaccia GUI Less MSieérables [lessmsi].
Created by=Creata da
with contribution from=con il contributo di
and others=e altri
This program uses a slightly modified of the libsmpack library.=Questo programma usa una versione leggermente modificata della libreria libsmpack.
The modified libsmpack source code is available from lessmsi website at=Il codice sorgente modificato di libsmpack è disponibile nel sito web lessmsi all'indirizzo
Table=Tabella
Name=Nome
Value=Valore
ID=ID
Type=Tipo
Description=Descrizione
Stream=Flusso
streaminbfo=Info stream
Extract Stream Files...=Estrai file flussi...

**Comment by activescott** [comment]
Thanks everyone! 

 @mega5800 For implementation, I am assuming these new languages would just be new resx files added to git and the msbuild project and would be compiled to .resources files and distributed with the binaries. Is that correct or are you thinking something else?

and this will only affect GUI right?

**Comment by mega5800** [comment]
Hello @activescott.

I will use resx files to support different languages based on user’s locale.
I will create a default file for English and another file for Italian.
This change will only effect the GUI, as bovirus requested.

In the meantime, are there any other languages you’d like to add to the GUI?

Thank you.

**Comment by activescott** [comment]
Sounds Great! Thank you for your efforts!

**Comment by mega5800** [comment]
@bovirus, thank you for the provided translations.

I miss the next phrases:
- Summary
- Recent Files

In addition, I would like to get translations for the next:

<ins>Error Phrases</ins>
- ERROR
- Error loading Summary Information
- Failed to open file
- Cannot view files
- Cannot view table
- File does not exist
- The file path contains invalid characters
- The file path is badly formed
- The file path is empty
- The file path is too long
- File does not exist

<ins>LessMSIerables Preferences</ins>
- Add Shortcut Item to Explorer
Adds 'Extract' & 'Explore' menu items to the right-click context menu of .msi files

- Remove Shortcut Item
Removes the context menu if it exists

![image](https://github.com/user-attachments/assets/c2ca4f1b-bad9-4406-9da0-42af1f4076e2)


Thank you.

**Comment by mega5800** [comment]
Hello @bovirus.

Any updates regarding the Italian texts I requested?

Thank you.

**Comment by bovirus** [comment]
Sorry for  delay.
I wrote the translation but seems disapperated.

Riepilogo
File recenti

- Error phhrases

ERRORE
Errore nel caricamento info riepilogo
Impossibile aprire il file
Impossibile visualizzare il file
Impossibile visualizzare la tabella
Il file non esiste
Il percorso del file contiene caratteri non validi
Il percorso del file ha un formato non valido
Il percorso è vuoto
Il percorso del file è troppo lungo
Il file non esiste

-Prefences

Aggiungi menu contestuale Explorer
Aggiungi le voci 'Estrai' e 'Sfoglia' al menu contestuale dei file .msi

Rimuovi menu contestuale Explorer
Rimuovi se esistono voci menu contestuale Explorer

Thanks

**Comment by mega5800** [comment]
Thank you @bovirus.

I need the next phrases:
- Missing File
- should be in the same directory as
![image](https://github.com/user-attachments/assets/99258cd6-9898-4a55-b52a-cde2c958d3f2)


- Copyright
- Could not find stream for
- Loading list of tables
- No files present
- files found
- Processing Table
- Please select some or all of the files to extract them

Thank you

**Comment by bovirus** [comment]
@mega5800 

File mancante

Il file 'AddWindowsExplorerShortcut' deve essere nella stessa cartella di less-gui.exe.

Copyright

Impossibile trovare lo stream per

Caricamento elenco tabelle

Nessun file presente

file trovati

Tabella elaborazione

Seleziona i file da estrarre

Cerca

Thanks.

**Comment by mega5800** [comment]
@bovirus, thank you for your help.

I believe I got all the necessary Italian texts and already created a pull request for @activescott to examine.
You can view some screenshots of the Italian GUI in the pull request message.
