### ISSUE TITLE
Version 2.2.0 - Translation issues / About window height not enough

### ISSUE THREAD

**Issue by bovirus** [activescott/lessmsi#206]
@mega5800 
@activescott 

**Describe the bug**

Some issue about strings untranslated

**To Reproduce**

Check screenshot

**Expected behavior**

The string should be translated

**Screenshots**

![image](https://github.com/user-attachments/assets/126b1293-e308-476b-ab58-216c9ceb7eab)
Strings highlighted are untranbslated
Add to language file

![image](https://github.com/user-attachments/assets/c7db3e08-236c-42bc-b529-3c6251871a89)
Strings highlighted are untranbslated
Add to language file
About window height is tto short. Incraese window height to avoid as much as possible scroll down.

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 64bit Italian
 - Browser: Google Chjrome
 - Version: 2.2.0

**Additional context**

**Comment by mega5800** [comment]
Hello @bovirus.

Thank you for creating this ticket.
I'd like to ask and clarify a few things.

1. What do you expect the see in the first screenshot?

2. It was Scott's decision to leave the About window untranslated.
If he'll change his mind, I can develop this part again.
In addition, using the mouse cursor you can resize the About window as you'd like.
The window will react accordingly and the text will be displayed using the new window size.

Thanks.

**Comment by bovirus** [comment]
1. That two extension types (msi executable/All files) are translated
2.  I don't undestrand why leave untranslated "About" window (the rest of the program is translated). I know that I can resize "About" windows size. I beleive that if you set  abigger default width/height for "About" window is not necessary for the user increase it manually.

**Comment by mega5800** [comment]
@activescott,
Up to you, if you would like to translate the two extension types and the About window in the GUI.

**Comment by activescott** [comment]
Yeah, I'm not interested in adding the complexity to translate the rtf file used in the about box. I just dno't think it's worth it - and ultimately it will not help users _use_ the product. I'll leave this open though as an item to fix the other two items (msi executable/All files)

**Comment by mega5800** [comment]
Thanks @activescott for your input.
I will start working on this ticket right away.

@bovirus, can you please provide the Italian translation for "All Files" and "msierablefiles".
Thank you.

**Comment by mega5800** [comment]
@bovirus, by the way, can you please also provide the correct translations that you added in your pull request?

This way I will be able to assist you faster with your ticket and pull request rather than taking care of each part separately.

**Comment by bovirus** [comment]
@activescott 

Please consider at least to incraese default widht/height for About window.
To avoid to increase to read better and to scroll as much as possible.

@mega5800 

 "All Files" -> "Tutti i file"
"msierablefiles" "File eseguibili .msi"

**Comment by mega5800** [comment]
Hello @bovirus.

Just wanted to update you that a pull request, with the translation suggestions you raised, was merged into the app.
I'd appreciate it if you could download the latest version of the app, and make sure  you are content with the final result.

Thank you.

**Comment by mega5800** [comment]
Hello @bovirus.

I hope you are content with the current state of the italian translations in the app.
If everthing works as you expect, can you please close this ticket?

If you have any issues, please let me know.

Thank you.
