### ISSUE TITLE
Using windows explorer context "Copy as path" output causes ArgumentException

### ISSUE THREAD

**Issue by AGBrown** [activescott/lessmsi#46]
Windows explorer (since Win 7) provides the "copy as path" context menu command to get file path. However it encapsulates the file path on the clipboard with double quotes (e.g. `"C:\path\to\my\file.txt"`). This causes `new FileInfo(txtMsiFileName.Text);` in `ReloadCurrentUIOnEnterKeyDown` to throw an `System.ArgumentException:  Illegal characters in path.`, or the user has to do some tedious <kbd>Home</kbd> <kbd>Delete</kbd> <kbd>End</kbd> <kbd>Backspace</kbd> editing each time.

Purely in the spirit of nice UX it would be good to handle paths contained in double quotes, and catch some of the common path exceptions from typos. I've built a two-line fix for the first part at  [AGBrown/lessmsi/9d73c374](https://github.com/AGBrown/lessmsi/commit/9d73c374a1314e45f5527c181260b3031b841dd1) and handling some of the possible exceptions for bad paths at [AGBrown/lessmsi/fa39baad](https://github.com/AGBrown/lessmsi/commit/fa39baad569f48e9cfacb09c496c35eb3925368d). Pull request to follow.

**Comment by activescott** [comment]
Appreciate this Andrew! I will test this out and merge as soon as I have a minute free from work. It will probably be this weekend. Thanks for the PR !

**Comment by AGBrown** [comment]
My pleasure Scott. It's a great little tool. 
On Thu, Feb 19, 2015 at 8:38 am, scott willeke <notifications@github.com> wrote:Appreciate this Andrew! I will test this out and merge as soon as I have a minute free from work. It will probably be this weekend. Thanks for the PR !

**Comment by activescott** [comment]
this was refactored a bit and merged. Thanks @AGBrown
