### ISSUE TITLE
error extracting from `X86 Debuggers And Tools-x86_en-us.msi`

### ISSUE THREAD

**Issue by ctaggart** [activescott/lessmsi#49]
![image](https://cloud.githubusercontent.com/assets/80104/6763629/b5b291c2-cf42-11e4-8a6c-5aec0b0ed821.png)

This is an msi that comes with WDK. If you need help locating it let me know.

C:\Program Files (x86)\Windows Kits\8.1\Debuggers\Redist\X86 Debuggers And Tools-x86_en-us.msi

**Comment by activescott** [comment]
@ctaggart I would love it if you could review this issue and confirm that it is fixed in release v1.3: https://github.com/activescott/lessmsi/releases/tag/v1.3

Thanks!!
