### ISSUE TITLE
Wix EXE's /MSI's 

### ISSUE THREAD

**Issue by necrose99** [activescott/lessmsi#56]
Used to -x or -extract would do, and Intel had zips... but no more... 
but to package drivers and no fluf to update server...... 
WIX tool kit makes EXE/MSI , cant get the msi out of exe anymore  "go for Intel inside" .  to just get at drivers. 
also rather handy to slip into USB/iso key , boot/wim so I don't have windows nagging about 10 drivers on dozens of machines.  (NTlite and done.  can add missing drives so on boot/setup they are installed. )

also it would be nice in some cases not to have to install WIXtoolkit. just to get at msi to use Lessmsi 

Point being is hopefully a plugin can be made to handle these pesky sob's, so msi unpack is more seamless from wix... 

[wix-unpacker.ps1.txt](https://github.com/activescott/lessmsi/files/139256/wix-unpacker.ps1.txt)
http://stackoverflow.com/questions/26749207/extract-contents-of-burn-bootstrapper
http://www.wrightfully.com/extracting-msi-files-without-running-the-installer

**Comment by activescott** [comment]
Huh?

**Comment by activescott** [comment]
I don't understand the request/report here so I'm closing this one. If you can clarify in a comment happy to reopen.

**Comment by necrose99** [comment]
I'm just hoping an **improved plugin** , might get at these painful  exe's that unpack to wixtoolset  MSI , so you can use lessmsi to unpack them without all the fuss, and more seamless , just pick exe you know has difficult to unpack msi , get msi or unpack it all. 
-- however at your leisure. 

some wix based MSI/other (wix exe unpack msi ) in the EXE , 
**IE drivers from Intel ** 
<p>or others so far <u>have been vexing to get at.</u>  thier CLI switcher that used to spit out an extracted folder or msi are now gone.  i was hoping to improve difficult to extract MSI or other like wise Pain in the..... but exe wrapped MSIs to just unpack all that crap in one step.  
some vendors make the drivers very difficult to unpack.  **ARCHER wifi** also like **Intel** you cant crack out the wix-msi easily....  , so its a very manual nag if you had say lots of workstations/laptops to image... </p>

uniextract161_noinst i grabbed.. http://www.legroom.net/software/uniextract  however it has not all that great a history some have been trojan-ized by some malware makers, so AV scanners blacklist them all, as bad even though origin comes out clean. also uses an amalgamation of tools etc all daisy-chained together.  I would prefer something more Trusted. 

if you have alot of machines to deploy , having them unpacked or via network push (updates) can at times be advantageous, however if thier isnt any network cards due to vendor being a pest..... 
means you have to add to machine Manually to get any other driver push'es from server etc. 

So yeah A plugin to Help Lessmsi , get at some of the more Vexing MSI's or exe's containing them 
would be a real plus.
