### ISSUE TITLE
choco fix for upcoming checksum requirement

### ISSUE THREAD

**Issue by activescott** [activescott/lessmsi#73]
Looks like for legacy (or ignorance) reasons lessmsi's choco package's [chocolateyInstall.ps1 file](https://github.com/activescott/lessmsi/blob/ee2a0df0cb1fb242a152af2334b687582b9a7fdf/src/.build/chocolateyInstall.ps1) is using [Install-ChocolateyZipPackage](https://github.com/chocolatey/choco/wiki/HelpersInstallChocolateyZipPackage#install-chocolateyzippackage). This will soon require a checksum (or maybe not since it is local?). In any case according to that doc should be using [Get-ChocolateyUnzip](https://github.com/chocolatey/choco/wiki/HelpersGetChocolateyUnzip] instead.

Asked for guidance on this at https://github.com/chocolatey/choco/issues/112#issuecomment-244585711

**Comment by ferventcoder** [comment]
Docs were not always as good as they are now - it's likely you just missed it. Plus LessMSI started with pulling the file from a remote source and when you took over, it's likely you converted it to a local source and it just worked. So there was no real reason to explore further changes.

The advantage of Get-ChocolateyUnzip is that it doesn't take the additional step of copying the zip somewhere else on the filesystem before extraction. So you only have one copy and less disk space used.
