### ISSUE TITLE
Extracting custom action binaries

### ISSUE THREAD

**Issue by WillSullivan** [activescott/lessmsi#76]
Would be nice if this also could extract binaries for custom actions as well.

**Comment by activescott** [comment]
Love the suggestion. Let me know if you (or anyone else!) is interested in contributing. Happy to help and support someone on this.

**Comment by activescott** [comment]
@WillSullivan in [v1.6.0](https://github.com/activescott/lessmsi/releases/tag/v1.6.0) I added support for extracting raw streams on a new "Streams" tab in the GUI. Is that what you need or are custom action binaries separate? If you could provide a specific msi and more detail about what you're after I might look into it next time I'm hacking on this project.
Of course, contributions are always welcome :)

**Comment by activescott** [comment]
To the best of my knowledge extracting streams actually accomplishes this ask. Since there hasn't been engagement on this I'm going to close it. If anyone has a concern or advice feel free to reopen.
