### ISSUE TITLE
Command line option "o" (open?) to "explore" via right-click causes crash

### ISSUE THREAD

**Issue by CollinChaffin** [activescott/lessmsi#77]
As title states, for some reason open the GUI and then manually opening any chosen MSI file is successful.  

To reproduce this bug, simply attempt to open or "Lessmsi explore" via the installed right-click entry that correctly (apparently) resolves in the registry to the following:  REG-SZ "C:\ProgramData\chocolatey\lib\lessmsi\tools\lessmsi.exe" o "%1" results in the following dotnet System.NullReferenceException crash and this window:

https://1drv.ms/i/s!AhSqjTYUuHPKgZ4A7cdHls9It44S_g
https://1drv.ms/i/s!AhSqjTYUuHPKgZ4BGmAfB8zKEUKPSw

![snag_2-1-2017_02-24-20](https://cloud.githubusercontent.com/assets/9301483/22499751/2bca0d42-e826-11e6-8511-af1adad9c03e.png)
![snag_2-1-2017_02-30-16](https://cloud.githubusercontent.com/assets/9301483/22499830/a1238d0c-e826-11e6-91e1-b4061a50b9ae.png)

**Comment by activescott** [comment]
I cannot reproduce this on Win8 x64. If you still have this problem please re-open the issue and let me now the following:
* Hit Debug and provide a callstack.
* Can you please see if it is specific to a particular msi file or not?
* Does it also happen on the command line or only via the explorer integration?
* Provide anything else you can about the environment to help repro (if you can try on another machine that would be helpful too).
