### ISSUE TITLE
Wixtracts.ExtractFiles keeps msi Record handles open

### ISSUE THREAD

**Issue by ramiabughazaleh** [activescott/lessmsi#84]
`Wixtracts.ExtractFiles` keeps some msi `Record` handles open.

I ran into this issue when I was directly calling Wixtracts.ExtractFiles and then when it was finished, immediately trying to open the msi file for writing.
In my case, for reference, I received the following exception:
`System.IO.FileLoadException: The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)`

I debugged the issue and it's because the `Record` objects are not being closed until they are garbage collected which may be some time in the future.

I will create a pull request.

Thank you.

**Comment by activescott** [comment]
Thanks so much for the PR @ramiabughazaleh . I'll try to get this tested on my side, merged, and into a release asap.
