### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by jjurkus** [activescott/lessmsi#90]
lessmsi-gui.exe and lessmsi.exe are crashing on startup, showing the default windows "... has stopped working" notice.

This is with version 1.6.1
If I remove all files in c:\Users\%userprofile%\AppData\Local\LessMsi\ it works again.
If I edit the user.cfg to remove all previous msi files (that don't exist anymore) it works again.

[lessmsi-gui.exe_Url_x0j5sudoke0qszxie0k512s0c5i5wuri.zip](https://github.com/activescott/lessmsi/files/1142058/lessmsi-gui.exe_Url_x0j5sudoke0qszxie0k512s0c5i5wuri.zip)

**Comment by activescott** [comment]
Bummer, but thank you for reporting this! I'll look into this when I have a moment. If you would like help preparing a fix and pull request let me know!

**Comment by jjurkus** [comment]
I can't program my way out of a cardboard box, so that's not going to help.

However, I have two different configuration files for you:
[lessmsi2342.zip](https://github.com/activescott/lessmsi/files/1174215/lessmsi2342.zip)

If I remove one previous file entry from the config file it works. Would I add a random item back, it will fail again. Maybe the reader of this part can't handle more than nine strings at a time?

**Comment by c0shea** [comment]
I have the same problem. Event Viewer reports the exception:

```
Application: lessmsi-gui.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
   at LessMsi.Gui.MruMenuStripManager.FixupMenuItems()
   at LessMsi.Gui.MruMenuStripManager.OnItemsChanged()
   at LessMsi.Gui.MruMenuStripManager.LoadPreferences()
   at LessMsi.Gui.MruMenuStripManager..ctor(System.Windows.Forms.ToolStripMenuItem)
   at LessMsi.Gui.MainForm..ctor(System.String)
   at LessMsi.Gui.Program.Main(System.String[])
```

**Comment by activescott** [comment]
Thanks for the note @c0shea ! If you would like help preparing a fix and pull request let me know!
