### ISSUE TITLE
LessMSI does not remember window size and position

### ISSUE THREAD

**Issue by bsto** [activescott/lessmsi#95]
Whenever I start lessmsi-gui.exe it is opened in the upper left corner as small window.

When I move and resize it then the new size and position is not remembered.

At next start I have to move and resize it again.
This is unnecessary and tedious.

Please add a remember option at exit to lessMSI

**Comment by activescott** [comment]
Thank you for the feedbck @bsto! I've put this on my list to address. I can't commit to a timeline just yet but I'll get to it as soon as I can.

**Comment by pstein** [comment]
I support this feature
Peter

**Comment by activescott** [comment]
The below articles are probably a good starting point for implementing this feature if someone is interested:

- https://www.arclab.com/en/kb/csharp/save-and-restore-position-size-windows-forms-application.html
- https://www.codeproject.com/Articles/15013/Windows-Forms-User-Settings-in-C
