### ISSUE TITLE
Issue using relative path to specify the msi file location

### ISSUE THREAD

**Issue by scottjbaldwin** [activescott/lessmsi#97]
when I attempt to run the following:
```
C:\MyFolder\>lessmsi x .\msi\mymsi.msi c:\extract\
```
Nothing is extracted

This is resolved if the full path is supplied e.g.

```
C:\MyFolder\>lessmsi x C:\MyFolder\msi\mymsi.msi c:\extract\
```
Not sure, but this may also relate to https://github.com/activescott/lessmsi/issues/91

**Comment by ysb33r** [comment]
I've noticed the same thing.

**Comment by manuelxmarquez** [comment]
Relative paths with .. also do not work. For example: C:\MyFolder\msi\..\setup\mymsi.msi
This appears to be an issue in LessIO. Not sure why the MS libraries are not being used.
