### ISSUE TITLE
lessmsi does nothing on microsoft/nanoserver

### ISSUE THREAD

**Issue by rismoney** [activescott/lessmsi#98]
trying to use this in a minimalistic container, and launching does not return anything.

**Comment by activescott** [comment]
Can you please provide more detail including steps to reproduce?

**Comment by rismoney** [comment]
is this using dotnet core or the regular version?

https://github.com/activescott/lessmsi/releases/latest

Easy to repro-
docker run -it --rm --entrypoint powershell.exe microsoft/nanoserver
spawn out (control-z)
download the lessmsi bits
and docker cp lessmsi.zip id:\
expand-archive
and run it.

**Comment by activescott** [comment]
@rismoney According to the overview at [here](https://blogs.technet.microsoft.com/windowsserver/2015/04/08/microsoft-announces-nano-server-for-modern-apps-and-cloud/), like nanoserver explicitly excludes the MSI stack (Windows Installer):

> To achieve these benefits, we removed the GUI stack, 32 bit support (WOW64), **MSI** and a number of default Server Core components.

Also noted [here](https://docs.microsoft.com/en-us/windows-server/get-started/deploy-nano-server):

> Windows Server App (WSA) installer provides a reliable installation option for Nano Server. **Since Windows Installer (MSI) is not supported on Nano Server**, WSA is also the only installation technology available for non-Microsoft products.

lessmsi does use the MSI native APIs under the covers, so without those it isn't going to work without some pretty significant work. It is possible to remove that dependency and read .msi files directly (lessmsi already does this for .cab files), but not a trivial change. WINE would be a good reference for that. I'd love to support any PRs if you or someone else has interest.
